---
- name: Install and configure Tomcat
  hosts: webservers
  become: yes
  tasks:
    - name: Install Java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present
    
    - name: Download Tomcat
      ansible.builtin.get_url:
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.83/bin/apache-tomcat-9.0.83.tar.gz
        dest: /opt/apache-tomcat-9.0.83.tar.gz

    - name: Extract Tomcat
      ansible.builtin.unarchive:
        src: /opt/apache-tomcat-9.0.83.tar.gz
        dest: /opt
        remote_src: yes

    - name: Start Tomcat service
      ansible.builtin.shell: /opt/apache-tomcat-9.0.83/bin/startup.sh
