---
- name: Deployment of WAR file
  hosts: webservers
  become: yes

  tasks:
    - name: Stop Tomcat service
      systemd:
        name: tomcat9
        state: stopped

    - name: Copy war file to tomcat webapp directory
      copy:
        src: target/addressbook.war
        dest: /var/lib/tomcat9/webapps/addressbook.war
        owner: tomcat9
        group: tomcat9
        mode: '0644'
    
    - name: Start Tomcat service
      systemd:
        name: tomcat9
        state: started
